# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e6bb8510e926050fe650f6669717d01082e74b0048221bbdb16a6fbd984f71fe9715bed2e6c2b52a12bf13615e157826775c126001559fd3ee59ed96875982

test:
  secret_key_base: d57db12154c9fb1100870ce8dbaa4f4aa1b53d4be6eacf8b6149d055411dab9ae4e6c9c297a7ec87e7cc4afe76b78a0637291d0b772713f9878ee18fe21ee5ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
